packages:
  - "packages/*"

# MiniPay security: reject packages published less than 7 days ago
minimumReleaseAge: 10080

allowBuilds:
  '@google/genai': true
  '@sentry/cli': true
  msgpackr-extract: true
  protobufjs: set this to true or false

onlyBuiltDependencies:
  - "@google/genai"
  - "@prisma/client"
  - "@prisma/engines"
  - bufferutil
  - esbuild
  - keccak
  - msgpackr-extract
  - prisma
  - protobufjs
  - secp256k1
  - sharp
  - utf-8-validate
