packages:
  - "packages/*"

onlyBuiltDependencies:
  - "@google/genai"
  - "@prisma/client"
  - "@prisma/engines"
  - bufferutil
  - esbuild
  - keccak
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - utf-8-validate
